### ISSUE TITLE
Problem with initial state of parcel finder

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-module-ui#6]
We have a problem with initial state of the parcel finder.
If we go to checkout, we have selected a "default country "Deutschland".
The block with the shipping options is loaded but WITHOUT the parcel finder.
This problem may be the same regarding the issue before netresearch/dhl-shipping-m2#12 

1. Product in Basket and proceed to checkout
=> Parcel finder is not visible and  Country is "Deutschland"
![Bildschirmfoto vom 2020-10-30 14-21-45](https://user-images.githubusercontent.com/25743167/97709847-442df080-1abb-11eb-83b6-d7b765489b4d.png)
2. Switch to country other than germany
=> Block is reloaded without parcel finder ... correct
![Bildschirmfoto vom 2020-10-30 14-22-44](https://user-images.githubusercontent.com/25743167/97709950-66277300-1abb-11eb-9117-9752b3bec8fb.png)
3. Switch back to "Deutschland"
=> Block is reloaded wit parcel finder ... correct
![Bildschirmfoto vom 2020-10-30 14-23-28](https://user-images.githubusercontent.com/25743167/97710020-7dfef700-1abb-11eb-9ee3-42214b3582ca.png)

I think the initial state/event is missing. The event for showing/reloading the block should be triggered after the page is loaded
and not only by changes from the country.
Greetings
Jan

**Comment by mam08ixo** [comment]
Caused by #5
