### ISSUE TITLE
Wrong language in Checkout-data API Call

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-module-ui#9]
We experienced a problem with the language in our shop.
Sometimes the language of the dhl shipping is german, sometimes english.

![Bildschirmfoto vom 2021-01-08 19-50-26](https://user-images.githubusercontent.com/25743167/104053082-f20bf880-51ea-11eb-9bc0-259a55f2dffd.png)

I debugged the problem and I think there is a caching (id) problem with the
/de/rest/de/V1/dhl/checkout-data/get API call.
The Dhl\ShippingCore\Model\ShippingSettings\Config\Reader in Line 93 uses for caching id a config id and the scope (like "frontend").
However, the store id is not part of the caching id.
The result:
- /de/rest/en/V1/dhl/checkout-data/get
First call caches the data inenglisch with the id: "dhl_shipping_option_configfrontend"
- /de/rest/de/V1/dhl/checkout-data/get
Second call gets the cached data in egnlish, but actually should be in german.

**Comment by mam08ixo** [comment]
Behavior was changed in version 1.2.3
